download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-mongodb-1.8.0.tar.gz
format_version: 1.0.0
name: mongodb
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.8.0
version_url: /api/content/published/v3/plugin/ansible/content/published/collections/index/community/mongodb/versions/1.8.0/
